### ISSUE TITLE
Phantom additional lines

### ISSUE THREAD

**Issue by woohung** [icealtria/obsidian-telegram-inbox#5]
Hi!

When i send message in telegram bot like this:

<img width="246" alt="image" src="https://github.com/icealtria/obsidian-telegram-inbox/assets/84230422/7345ce09-63b6-4109-b81b-2fb707f7021f">

In Obsidian, I get an additional line inside code block and between "created" and the text, it looks like a bug.

![image](https://github.com/icealtria/obsidian-telegram-inbox/assets/84230422/b813c241-c19e-43da-ba6e-109e088cf7b0)

But if I send only a block of code, there are no problems with additional lines inside the block.

My message template is:
```
Created: <% tp.file.creation_date("Do MMMM YYYY") %>
{{title}}
{{{text}}}
```
My custom path is:
```
Telegram/{{date}}/{{time}}.md
```

P.S. I just started research the tool, maybe I'm doing something wrong, I'll be grateful if you correct it. Thnx.

**Comment by icealtria** [comment]
The blank line between Created and `{{{text}}}` is because the `{{title}}` is not available. Therefore, it renders as a blank line. You can refer to the available fields at [wiki](https://github.com/icealtria/obsidian-telegram-inbox/wiki/Message-template).

I could not reproduce the code block with additional line in it.
